# This is a basic workflow that is manually triggered

name: Release

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#    paths:
#      - ".github/workflows/release.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install Nativefier
        run: npm install -g nativefier
        #if: steps.shouldrun.outputs.shouldrun == 1
      - name: Get nativefier version
        run: echo "::set-output name=nativefier-version::$(nativefier --version)"
        id: nativefier-version
      - name: Setup Nativefier Dependencies
        run: sudo apt-get update && sudo apt-get --yes install wine64 imagemagick
      - name: Build
        run: |
          nativefier --version
          NATIVEFIERELECTRONVERSION=${{ github.event.inputs.electron-version }} #$(npm show electron version)
          echo $NATIVEFIERELECTRONVERSION
          nativefier "https://youtube.com/tv" -u "Roku/DVP-9.10 (519.10E04111A)" -n "YouTube on TV" -p osx
          mv YouTube\ on\ TV-darwin-x64 YouTubeonTV-darwin-x64
          zip YouTubeonTV-darwin-x64.zip -r YouTubeonTV-darwin-x64 > /dev/null 2>&1
          nativefier "https://youtube.com/tv" -u "Roku/DVP-9.10 (519.10E04111A)" -n "YouTube on TV" -p osx -a arm64
          mv YouTube\ on\ TV-darwin-arm64 YouTubeonTV-darwin-arm64
          zip YouTubeonTV-darwin-arm64.zip -r YouTubeonTV-darwin-arm64 > /dev/null 2>&1
          nativefier "https://youtube.com/tv" -u "Roku/DVP-9.10 (519.10E04111A)" -n "YouTube on TV" -p windows
          mv YouTube\ on\ TV-win32-x64 YouTubeonTV-win32-x64
          zip YouTubeonTV-win32-x64.zip -r YouTubeonTV-win32-x64 > /dev/null 2>&1
          nativefier "https://youtube.com/tv" -u "Roku/DVP-9.10 (519.10E04111A)" -n "YouTube on TV" -p windows -a arm64
          mv YouTube\ on\ TV-win32-arm64 YouTubeonTV-win32-arm64
          zip YouTubeonTV-win32-arm64.zip -r YouTubeonTV-win32-arm64 > /dev/null 2>&1
          nativefier "https://youtube.com/tv" -u "Roku/DVP-9.10 (519.10E04111A)" -n "YouTube on TV" -p linux -a arm64
          zip YouTubeonTV-linux-arm64.zip -r YouTubeonTV-linux-arm64 > /dev/null 2>&1
          nativefier "https://youtube.com/tv" -u "Roku/DVP-9.10 (519.10E04111A)" -n "YouTube on TV" -p linux -a x64
          zip YouTubeonTV-linux-x64.zip -r YouTubeonTV-linux-x64 > /dev/null 2>&1
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          tag: ${{ steps.nativefier-version.outputs.nativefier-version }},${{ github.event.inputs.electron-version }}
          name: v${{ steps.nativefier-version.outputs.nativefier-version }},${{ github.event.inputs.electron-version }} Nativefier ${{ steps.nativefier-version.outputs.nativefier-version }} Electron ${{ github.event.inputs.electron-version }}
