# This is a basic workflow that is manually triggered

name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install Nativefier
        run: npm install -g nativefier
      - name: Setup Dependencies
        run: sudo apt-get update && sudo apt-get --yes install wine64 imagemagick libfuse2
      - name: Build YouTubeTV
        run: |
          bash build.sh youtube

      - name: Publish Arifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./export/*.*