# This is a basic workflow that is manually triggered

name: Release

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#    paths:
#      - ".github/workflows/release.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install Nativefier
        run: npm install -g nativefier
        #if: steps.shouldrun.outputs.shouldrun == 1
      - name: Get nativefier version
        run: echo "::set-output name=nativefier-version::$(nativefier --version)"
        id: nativefier-version
      - name: Setup Nativefier Dependencies
        run: sudo apt-get update && sudo apt-get --yes install wine64 imagemagick
      - name: Build
        run: |
          bash build.sh ./configs/youtube.config.json

      - name: Publish Arifacts
        uses: actions/upload-artifact@v2
        with:
          name: YouTubeonTV-linux-x64
          path: *.zip